### ISSUE TITLE
Firefox tab chrashing on Hub and geckodriver install profile

### ISSUE THREAD

**Issue by Micky002** [willhaben/willtest#9]
New Firefox uses a feature called multi-process-tabs. This feature causes the tests to chrash on the selenium-hub. Error message from Firefox is "Gah. Your tab just crashed!!!".

By setting this two properties in the firefox-profile the feature is turned off.

```
firefoxProfile.setPreference("browser.tabs.remote.autostart.2", false);
firefoxProfile.setPreference("browser.tabs.remote.autostart", false);
```

Fix for the install of geckodriver on a Windows x64 machine.

**Comment by liptga** [comment]
Fixed in 1.1.1
